using System;
using System.Collections.Generic;
using UnityEngine.Localization.Settings;

public static class WordSets
{
    private static Random random = new Random();

    private static readonly List<WordSet> sets_nl = new List<WordSet>
    {
        new WordSet {InsiderWord = "Voetbal", OutsiderWord = "Bal"},
        new WordSet {InsiderWord = "Fiets", OutsiderWord = "Trappers"},
        new WordSet {InsiderWord = "TikTok", OutsiderWord = "Dansje"},
        new WordSet {InsiderWord = "Games", OutsiderWord = "Controller"},
        new WordSet {InsiderWord = "Netflix", OutsiderWord = "Aflevering"},
        new WordSet {InsiderWord = "Koken", OutsiderWord = "Pan"},
        new WordSet {InsiderWord = "Fotografie", OutsiderWord = "Camera"},
        new WordSet {InsiderWord = "Concert", OutsiderWord = "Muziek"},
        new WordSet {InsiderWord = "Sneakers", OutsiderWord = "Veters"},
        new WordSet {InsiderWord = "Winkelen", OutsiderWord = "Tas"},
        new WordSet {InsiderWord = "Kunst", OutsiderWord = "Verf"},
        new WordSet {InsiderWord = "Boek", OutsiderWord = "Bladzijden"},
        new WordSet {InsiderWord = "Pizza", OutsiderWord = "Kaas"},
        new WordSet {InsiderWord = "WhatsApp", OutsiderWord = "Bericht"},
        new WordSet {InsiderWord = "Festival", OutsiderWord = "Podium"},
        new WordSet {InsiderWord = "Hardlopen", OutsiderWord = "Schoenen"},
        new WordSet {InsiderWord = "Musical", OutsiderWord = "Zingen"},
        new WordSet {InsiderWord = "Hond", OutsiderWord = "Riem"},
        new WordSet {InsiderWord = "Wandelen", OutsiderWord = "Bos"},
        new WordSet {InsiderWord = "Strand", OutsiderWord = "Zand"},
        new WordSet {InsiderWord = "Gitaar", OutsiderWord = "Snaren"},
        new WordSet {InsiderWord = "Vissen", OutsiderWord = "Hengel"},
        new WordSet {InsiderWord = "Zeilen", OutsiderWord = "Boot"},
        new WordSet {InsiderWord = "Zwemmen", OutsiderWord = "Water"},
        new WordSet {InsiderWord = "Schaken", OutsiderWord = "Koning"},
        new WordSet {InsiderWord = "Lego", OutsiderWord = "Stenen"},
        new WordSet {InsiderWord = "Paardrijden", OutsiderWord = "Zadel"},
        new WordSet {InsiderWord = "Bioscoop", OutsiderWord = "Scherm"},
        new WordSet {InsiderWord = "Tuinieren", OutsiderWord = "Bloemen"},
        new WordSet {InsiderWord = "Voetbalstadion", OutsiderWord = "Tribune"},
        new WordSet {InsiderWord = "Koffie", OutsiderWord = "Beker"},
        new WordSet {InsiderWord = "IJssalon", OutsiderWord = "Bolletjes"},
        new WordSet {InsiderWord = "Pretpark", OutsiderWord = "Achtbaan"},
        new WordSet {InsiderWord = "Camping", OutsiderWord = "Tent"},
        new WordSet {InsiderWord = "Boerderij", OutsiderWord = "Dieren"},
        new WordSet {InsiderWord = "Markt", OutsiderWord = "Kraampje"},
        new WordSet {InsiderWord = "Koekjes", OutsiderWord = "Deeg"},
        new WordSet {InsiderWord = "Kerst", OutsiderWord = "Lichtjes"},
        new WordSet {InsiderWord = "Carnaval", OutsiderWord = "Masker"},
        new WordSet {InsiderWord = "Bakken", OutsiderWord = "Recept"},
        new WordSet {InsiderWord = "Vliegeren", OutsiderWord = "Wind"},
        new WordSet {InsiderWord = "Hockey", OutsiderWord = "Stick"},
        new WordSet {InsiderWord = "Schaatsen", OutsiderWord = "IJsbaan"},
        new WordSet {InsiderWord = "Kermis", OutsiderWord = "Rit"},
        new WordSet {InsiderWord = "Quiz", OutsiderWord = "Vraag"},
        new WordSet {InsiderWord = "Kleding", OutsiderWord = "Maat"},
        new WordSet {InsiderWord = "Darten", OutsiderWord = "Bord"},
        new WordSet {InsiderWord = "Darten", OutsiderWord = "Pijlen"},
        new WordSet {InsiderWord = "Kaarten", OutsiderWord = "Stapel"},
        new WordSet {InsiderWord = "Kaarten", OutsiderWord = "Schudden"},
        new WordSet {InsiderWord = "Terras", OutsiderWord = "Stoel"},
        new WordSet {InsiderWord = "Bier", OutsiderWord = "Schuim"},
        new WordSet {InsiderWord = "Wijn", OutsiderWord = "Glas"},
        new WordSet {InsiderWord = "Chocolade", OutsiderWord = "Reep"},
        new WordSet {InsiderWord = "Reizen", OutsiderWord = "Koffer"},
        new WordSet {InsiderWord = "Koken", OutsiderWord = "Ingrediënten"},
        new WordSet {InsiderWord = "Gaming", OutsiderWord = "Headset"},
        new WordSet {InsiderWord = "Piano", OutsiderWord = "Toetsen"},
        new WordSet {InsiderWord = "Tennis", OutsiderWord = "Racket"},
        new WordSet {InsiderWord = "Museum", OutsiderWord = "Galerij"},
        new WordSet {InsiderWord = "Kamperen", OutsiderWord = "Slaapzak"},
        new WordSet {InsiderWord = "DJ", OutsiderWord = "Mix"},
        new WordSet {InsiderWord = "Mode", OutsiderWord = "Outfit"},
        new WordSet {InsiderWord = "Zonsondergang", OutsiderWord = "Horizon"},
        new WordSet {InsiderWord = "Kitesurfen", OutsiderWord = "Golven"},
        new WordSet {InsiderWord = "Knuffel", OutsiderWord = "Kussen"},
        new WordSet {InsiderWord = "Popmuziek", OutsiderWord = "Hits"},
        new WordSet {InsiderWord = "Escape room", OutsiderWord = "Puzzel"},
        new WordSet {InsiderWord = "Puzzel", OutsiderWord = "Stukjes"},
        new WordSet {InsiderWord = "Karaoke", OutsiderWord = "Microfoon"},
        new WordSet {InsiderWord = "Fotobewerking", OutsiderWord = "Filters"},
        new WordSet {InsiderWord = "Festival", OutsiderWord = "Muntjes"},
        new WordSet {InsiderWord = "Speelhal", OutsiderWord = "Muntjes"},
        new WordSet {InsiderWord = "Vriendengroep", OutsiderWord = "Appje"},
        new WordSet {InsiderWord = "Klimmen", OutsiderWord = "Touw"},
        new WordSet {InsiderWord = "Boogschieten", OutsiderWord = "Pijl"},
        new WordSet {InsiderWord = "Zandkastelen", OutsiderWord = "Emmer"},
        new WordSet {InsiderWord = "Schep", OutsiderWord = "Emmer"},
        new WordSet {InsiderWord = "Drones", OutsiderWord = "Propellers"},
        new WordSet {InsiderWord = "Schilderen", OutsiderWord = "Doek"},
        new WordSet {InsiderWord = "Skateboarden", OutsiderWord = "Ramp"},
        new WordSet {InsiderWord = "Racen", OutsiderWord = "Bocht"},
        new WordSet {InsiderWord = "Paard", OutsiderWord = "Manen"},
        new WordSet {InsiderWord = "Zomer", OutsiderWord = "Zon"},
        new WordSet {InsiderWord = "Winter", OutsiderWord = "Sneeuw"},
        new WordSet {InsiderWord = "Herfst", OutsiderWord = "Bladeren"},
        new WordSet {InsiderWord = "Lente", OutsiderWord = "Bloesem"},
        new WordSet {InsiderWord = "Wandelen", OutsiderWord = "Paden"},
        new WordSet {InsiderWord = "Sushi", OutsiderWord = "Rijst"},
        new WordSet {InsiderWord = "Avocado", OutsiderWord = "Toast"},
        new WordSet {InsiderWord = "Yoga", OutsiderWord = "Mat"},
        new WordSet {InsiderWord = "Workout", OutsiderWord = "Gewichten"},
        new WordSet {InsiderWord = "Fitness", OutsiderWord = "Spieren"},
        new WordSet {InsiderWord = "Karten", OutsiderWord = "Helm"},
        new WordSet {InsiderWord = "Lasergamen", OutsiderWord = "Stralen"},
        new WordSet {InsiderWord = "Knutselen", OutsiderWord = "Schaar"},
        new WordSet {InsiderWord = "Theater", OutsiderWord = "Acteurs"},
        new WordSet {InsiderWord = "Fotografie", OutsiderWord = "Lens"},
        new WordSet {InsiderWord = "Bioscoop", OutsiderWord = "Popcorn"},
        new WordSet {InsiderWord = "Aquarel", OutsiderWord = "Kwast"},
        new WordSet {InsiderWord = "Fietstocht", OutsiderWord = "Route"},
        new WordSet {InsiderWord = "Surfen", OutsiderWord = "Plank"},
        new WordSet {InsiderWord = "Bergbeklimmen", OutsiderWord = "Rotsen"},
        new WordSet {InsiderWord = "Zeilen", OutsiderWord = "Mast"},
        new WordSet {InsiderWord = "Rolschaatsen", OutsiderWord = "Wieltjes"},
        new WordSet {InsiderWord = "Wielrennen", OutsiderWord = "Fietsketting"},
        new WordSet {InsiderWord = "Schilderij", OutsiderWord = "Lijst"},
        new WordSet {InsiderWord = "Tekenen", OutsiderWord = "Potlood"},
        new WordSet {InsiderWord = "Podcast", OutsiderWord = "Stem"},
        new WordSet {InsiderWord = "Zomerfestival", OutsiderWord = "Vuurwerk"},
        new WordSet {InsiderWord = "Drummen", OutsiderWord = "Stokken"},
        new WordSet {InsiderWord = "Tuinfeest", OutsiderWord = "Lampionnen"},
        new WordSet {InsiderWord = "Pretpark", OutsiderWord = "Attracties"},
        new WordSet {InsiderWord = "Carnaval", OutsiderWord = "Kostuum"},
        new WordSet {InsiderWord = "Strandwandeling", OutsiderWord = "Schelp"},
        new WordSet {InsiderWord = "Mountainbike", OutsiderWord = "Banden"},
        new WordSet {InsiderWord = "Pianospelen", OutsiderWord = "Muzieknoten"},
        new WordSet {InsiderWord = "Boetseren", OutsiderWord = "Klei"},
        new WordSet {InsiderWord = "Boekenclub", OutsiderWord = "Hoofdstuk"},
        new WordSet {InsiderWord = "Marktplaats", OutsiderWord = "Advertentie"},
        new WordSet {InsiderWord = "Schaaktoernooi", OutsiderWord = "Bord"},
        new WordSet {InsiderWord = "Zomerkamp", OutsiderWord = "Vriendschap"},
        new WordSet {InsiderWord = "Groepsfoto", OutsiderWord = "Lach"},
        new WordSet {InsiderWord = "Zangwedstrijd", OutsiderWord = "Stem"},
        new WordSet {InsiderWord = "Streetdance", OutsiderWord = "Moves"},
        new WordSet {InsiderWord = "Beachvolleybal", OutsiderWord = "Net"},
        new WordSet {InsiderWord = "Duiken", OutsiderWord = "Flippers"},
        new WordSet {InsiderWord = "Roadtrip", OutsiderWord = "Kaart"},
        new WordSet {InsiderWord = "Klimpark", OutsiderWord = "Harnas"},
        new WordSet {InsiderWord = "Bordspel", OutsiderWord = "Dobbelsteen"},
        new WordSet {InsiderWord = "Kamperen", OutsiderWord = "Vuur"},
        new WordSet {InsiderWord = "Streetfood", OutsiderWord = "Kraampje"},
        new WordSet {InsiderWord = "Tuinieren", OutsiderWord = "Schep"},
        new WordSet {InsiderWord = "Zonnebaden", OutsiderWord = "Handdoek"},
        new WordSet {InsiderWord = "Winterwandeling", OutsiderWord = "Sjaal"},
        new WordSet {InsiderWord = "Filmavond", OutsiderWord = "Bank"},
        new WordSet {InsiderWord = "Fotowandeling", OutsiderWord = "Natuur"},
        new WordSet {InsiderWord = "Boulderen", OutsiderWord = "Muur"},
        new WordSet {InsiderWord = "Airsoft", OutsiderWord = "Masker"},
        new WordSet {InsiderWord = "Kookclub", OutsiderWord = "Recepten"},
        new WordSet {InsiderWord = "Kerstmarkt", OutsiderWord = "Kraampjes"},
        new WordSet {InsiderWord = "Kampvuur", OutsiderWord = "Vlammen"},
        new WordSet {InsiderWord = "Halloween", OutsiderWord = "Schaduw"},
        new WordSet {InsiderWord = "Tekenwedstrijd", OutsiderWord = "Portret"},
        new WordSet {InsiderWord = "Paaseieren zoeken", OutsiderWord = "Mandje"},
        new WordSet {InsiderWord = "Gala", OutsiderWord = "Jurk"},
        new WordSet {InsiderWord = "Geocaching", OutsiderWord = "Schat"},
        new WordSet {InsiderWord = "Jeu de boules", OutsiderWord = "Bal"},
        new WordSet {InsiderWord = "Zomervakantie", OutsiderWord = "Koffer"},
        new WordSet {InsiderWord = "Zwemles", OutsiderWord = "Slagen"},
        new WordSet {InsiderWord = "Lego bouwen", OutsiderWord = "Blokjes"},
        new WordSet {InsiderWord = "Modeltreinen", OutsiderWord = "Rails"},
        new WordSet {InsiderWord = "Parkour", OutsiderWord = "Muur"},
        new WordSet {InsiderWord = "Bungeejumpen", OutsiderWord = "Diepte"},
        new WordSet {InsiderWord = "Waterpolo", OutsiderWord = "Bal"},
        new WordSet {InsiderWord = "Schuimparty", OutsiderWord = "Bellen"},
        new WordSet {InsiderWord = "Streetfoodmarkt", OutsiderWord = "Geuren"},
        new WordSet {InsiderWord = "Videobewerking", OutsiderWord = "Clips"},
        new WordSet {InsiderWord = "Basketbalwedstrijd", OutsiderWord = "Dribbel"},
        new WordSet {InsiderWord = "Dierentuin", OutsiderWord = "Kooi"},
        new WordSet {InsiderWord = "Duinwandeling", OutsiderWord = "Zand"},
        new WordSet {InsiderWord = "Filmfestival", OutsiderWord = "Première"},
        new WordSet {InsiderWord = "Waterballonnengevecht", OutsiderWord = "Spetters"},
        new WordSet {InsiderWord = "Nachtzwemmen", OutsiderWord = "Sterren"},
        new WordSet {InsiderWord = "Trampolinespringen", OutsiderWord = "Sprongen"},
        new WordSet {InsiderWord = "Streetart", OutsiderWord = "Graffiti"},
        new WordSet {InsiderWord = "Tattoo", OutsiderWord = "Naald"},
        new WordSet {InsiderWord = "Graffiti", OutsiderWord = "Spuitbus"},
        new WordSet {InsiderWord = "Midzomerfeest", OutsiderWord = "Fakkels"},
        new WordSet {InsiderWord = "Vuurwerkshow", OutsiderWord = "Knal"},
        new WordSet {InsiderWord = "Parachutespringen", OutsiderWord = "Val"},
        new WordSet {InsiderWord = "Snorkelen", OutsiderWord = "Visjes"},
        new WordSet {InsiderWord = "Klimhal", OutsiderWord = "Grepen"},
        new WordSet {InsiderWord = "Rivierwandeling", OutsiderWord = "Stenen"},
        new WordSet {InsiderWord = "Stadswandeling", OutsiderWord = "Gids"},
        new WordSet {InsiderWord = "Strandvolleybal", OutsiderWord = "Zand"},
        new WordSet {InsiderWord = "Coffeeshop", OutsiderWord = "Bonen"},
        new WordSet {InsiderWord = "Luchtballonvaart", OutsiderWord = "Mand"},
        new WordSet {InsiderWord = "Zandkastelen", OutsiderWord = "Schep"},
        new WordSet {InsiderWord = "Paintball", OutsiderWord = "Masker"},
        new WordSet {InsiderWord = "Parkfestival", OutsiderWord = "Dekens"},
        new WordSet {InsiderWord = "Droneshow", OutsiderWord = "Figuren"},
        new WordSet {InsiderWord = "Goochelen", OutsiderWord = "Kaarten"},
        new WordSet {InsiderWord = "Magische show", OutsiderWord = "Illusie"},
        new WordSet {InsiderWord = "Circus", OutsiderWord = "Clown"},
        new WordSet {InsiderWord = "Reuzenrad", OutsiderWord = "Uitzicht"},
        new WordSet {InsiderWord = "Sterrenkijken", OutsiderWord = "Telescoop"},
        new WordSet {InsiderWord = "Vlotvaren", OutsiderWord = "Hout"},
        new WordSet {InsiderWord = "Weerwolvenspel", OutsiderWord = "Kaarten"},
        new WordSet {InsiderWord = "Kaarsen maken", OutsiderWord = "Was"},
        new WordSet {InsiderWord = "Kringspel", OutsiderWord = "Cirkel"},
        new WordSet {InsiderWord = "Strandjutten", OutsiderWord = "Schatten"},
        new WordSet {InsiderWord = "Lantaarnoptocht", OutsiderWord = "Lichtjes"},
        new WordSet {InsiderWord = "Kanoën", OutsiderWord = "Peddel"},
        new WordSet {InsiderWord = "Paardenrennen", OutsiderWord = "Finish"},
        new WordSet {InsiderWord = "Zandbakspelen", OutsiderWord = "Vormpjes"},
        new WordSet {InsiderWord = "Picknick", OutsiderWord = "Mand"},
        new WordSet {InsiderWord = "Luchtkussenfeest", OutsiderWord = "Springen"},
        new WordSet {InsiderWord = "Fotocollage", OutsiderWord = "Plakboek"},
        new WordSet {InsiderWord = "Vliegerwedstrijd", OutsiderWord = "Koord"},
        new WordSet {InsiderWord = "Vogels spotten", OutsiderWord = "Verrekijker"},
        new WordSet {InsiderWord = "Lampionnenfestival", OutsiderWord = "Schijnsel"},
        new WordSet {InsiderWord = "Avonturenpark", OutsiderWord = "Klimmen"}
    };

    private static readonly List<WordSet> sets_en = new List<WordSet>
    {
        new WordSet {InsiderWord = "Football", OutsiderWord = "Ball"},
        new WordSet {InsiderWord = "Bicycle", OutsiderWord = "Pedals"},
        new WordSet {InsiderWord = "TikTok", OutsiderWord = "Dance"},
        new WordSet {InsiderWord = "Games", OutsiderWord = "Controller"},
        new WordSet {InsiderWord = "Netflix", OutsiderWord = "Episode"},
        new WordSet {InsiderWord = "Cooking", OutsiderWord = "Pan"},
        new WordSet {InsiderWord = "Photography", OutsiderWord = "Camera"},
        new WordSet {InsiderWord = "Concert", OutsiderWord = "Music"},
        new WordSet {InsiderWord = "Sneakers", OutsiderWord = "Laces"},
        new WordSet {InsiderWord = "Shopping", OutsiderWord = "Bag"},
        new WordSet {InsiderWord = "Art", OutsiderWord = "Paint"},
        new WordSet {InsiderWord = "Book", OutsiderWord = "Pages"},
        new WordSet {InsiderWord = "Pizza", OutsiderWord = "Cheese"},
        new WordSet {InsiderWord = "WhatsApp", OutsiderWord = "Message"},
        new WordSet {InsiderWord = "Festival", OutsiderWord = "Stage"},
        new WordSet {InsiderWord = "Running", OutsiderWord = "Shoes"},
        new WordSet {InsiderWord = "Musical", OutsiderWord = "Singing"},
        new WordSet {InsiderWord = "Dog", OutsiderWord = "Leash"},
        new WordSet {InsiderWord = "Walking", OutsiderWord = "Forest"},
        new WordSet {InsiderWord = "Beach", OutsiderWord = "Sand"},
        new WordSet {InsiderWord = "Guitar", OutsiderWord = "Strings"},
        new WordSet {InsiderWord = "Fishing", OutsiderWord = "Rod"},
        new WordSet {InsiderWord = "Sailing", OutsiderWord = "Boat"},
        new WordSet {InsiderWord = "Swimming", OutsiderWord = "Water"},
        new WordSet {InsiderWord = "Chess", OutsiderWord = "King"},
        new WordSet {InsiderWord = "Lego", OutsiderWord = "Bricks"},
        new WordSet {InsiderWord = "Horseback Riding", OutsiderWord = "Saddle"},
        new WordSet {InsiderWord = "Cinema", OutsiderWord = "Screen"},
        new WordSet {InsiderWord = "Gardening", OutsiderWord = "Flowers"},
        new WordSet {InsiderWord = "Football Stadium", OutsiderWord = "Stand"},
        new WordSet {InsiderWord = "Coffee", OutsiderWord = "Cup"},
        new WordSet {InsiderWord = "Ice Cream Shop", OutsiderWord = "Scoops"},
        new WordSet {InsiderWord = "Theme Park", OutsiderWord = "Roller Coaster"},
        new WordSet {InsiderWord = "Camping", OutsiderWord = "Tent"},
        new WordSet {InsiderWord = "Farm", OutsiderWord = "Animals"},
        new WordSet {InsiderWord = "Market", OutsiderWord = "Stall"},
        new WordSet {InsiderWord = "Cookies", OutsiderWord = "Dough"},
        new WordSet {InsiderWord = "Christmas", OutsiderWord = "Lights"},
        new WordSet {InsiderWord = "Carnival", OutsiderWord = "Mask"},
        new WordSet {InsiderWord = "Baking", OutsiderWord = "Recipe"},
        new WordSet {InsiderWord = "Kite Flying", OutsiderWord = "Wind"},
        new WordSet {InsiderWord = "Hockey", OutsiderWord = "Stick"},
        new WordSet {InsiderWord = "Ice Skating", OutsiderWord = "Rink"},
        new WordSet {InsiderWord = "Fair", OutsiderWord = "Ride"},
        new WordSet {InsiderWord = "Quiz", OutsiderWord = "Question"},
        new WordSet {InsiderWord = "Clothing", OutsiderWord = "Size"},
        new WordSet {InsiderWord = "Darts", OutsiderWord = "Board"},
        new WordSet {InsiderWord = "Darts", OutsiderWord = "Darts"},
        new WordSet {InsiderWord = "Cards", OutsiderWord = "Deck"},
        new WordSet {InsiderWord = "Cards", OutsiderWord = "Shuffle"},
        new WordSet {InsiderWord = "Terrace", OutsiderWord = "Chair"},
        new WordSet {InsiderWord = "Beer", OutsiderWord = "Foam"},
        new WordSet {InsiderWord = "Wine", OutsiderWord = "Glass"},
        new WordSet {InsiderWord = "Chocolate", OutsiderWord = "Bar"},
        new WordSet {InsiderWord = "Traveling", OutsiderWord = "Suitcase"},
        new WordSet {InsiderWord = "Cooking", OutsiderWord = "Ingredients"},
        new WordSet {InsiderWord = "Gaming", OutsiderWord = "Headset"},
        new WordSet {InsiderWord = "Piano", OutsiderWord = "Keys"},
        new WordSet {InsiderWord = "Tennis", OutsiderWord = "Racket"},
        new WordSet {InsiderWord = "Museum", OutsiderWord = "Gallery"},
        new WordSet {InsiderWord = "Camping", OutsiderWord = "Sleeping Bag"},
        new WordSet {InsiderWord = "DJ", OutsiderWord = "Mix"},
        new WordSet {InsiderWord = "Fashion", OutsiderWord = "Outfit"},
        new WordSet {InsiderWord = "Sunset", OutsiderWord = "Horizon"},
        new WordSet {InsiderWord = "Kitesurfing", OutsiderWord = "Waves"},
        new WordSet {InsiderWord = "Teddy Bear", OutsiderWord = "Pillow"},
        new WordSet {InsiderWord = "Pop Music", OutsiderWord = "Hits"},
        new WordSet {InsiderWord = "Escape Room", OutsiderWord = "Puzzle"},
        new WordSet {InsiderWord = "Puzzle", OutsiderWord = "Pieces"},
        new WordSet {InsiderWord = "Karaoke", OutsiderWord = "Microphone"},
        new WordSet {InsiderWord = "Photo Editing", OutsiderWord = "Filters"},
        new WordSet {InsiderWord = "Festival", OutsiderWord = "Tokens"},
        new WordSet {InsiderWord = "Arcade", OutsiderWord = "Tokens"},
        new WordSet {InsiderWord = "Friend Group", OutsiderWord = "Message"},
        new WordSet {InsiderWord = "Climbing", OutsiderWord = "Rope"},
        new WordSet {InsiderWord = "Archery", OutsiderWord = "Arrow"},
        new WordSet {InsiderWord = "Sandcastles", OutsiderWord = "Bucket"},
        new WordSet {InsiderWord = "Shovel", OutsiderWord = "Bucket"},
        new WordSet {InsiderWord = "Drones", OutsiderWord = "Propellers"},
        new WordSet {InsiderWord = "Painting", OutsiderWord = "Canvas"},
        new WordSet {InsiderWord = "Skateboarding", OutsiderWord = "Ramp"},
        new WordSet {InsiderWord = "Racing", OutsiderWord = "Turn"},
        new WordSet {InsiderWord = "Horse", OutsiderWord = "Mane"},
        new WordSet {InsiderWord = "Summer", OutsiderWord = "Sun"},
        new WordSet {InsiderWord = "Winter", OutsiderWord = "Snow"},
        new WordSet {InsiderWord = "Autumn", OutsiderWord = "Leaves"},
        new WordSet {InsiderWord = "Spring", OutsiderWord = "Blossom"},
        new WordSet {InsiderWord = "Walking", OutsiderWord = "Paths"},
        new WordSet {InsiderWord = "Sushi", OutsiderWord = "Rice"},
        new WordSet {InsiderWord = "Avocado", OutsiderWord = "Toast"},
        new WordSet {InsiderWord = "Yoga", OutsiderWord = "Mat"},
        new WordSet {InsiderWord = "Workout", OutsiderWord = "Weights"},
        new WordSet {InsiderWord = "Fitness", OutsiderWord = "Muscles"},
        new WordSet {InsiderWord = "Go-Karting", OutsiderWord = "Helmet"},
        new WordSet {InsiderWord = "Laser Tag", OutsiderWord = "Beams"},
        new WordSet {InsiderWord = "Crafts", OutsiderWord = "Scissors"},
        new WordSet {InsiderWord = "Theater", OutsiderWord = "Actors"},
        new WordSet {InsiderWord = "Photography", OutsiderWord = "Lens"},
        new WordSet {InsiderWord = "Cinema", OutsiderWord = "Popcorn"},
        new WordSet {InsiderWord = "Watercolor", OutsiderWord = "Brush"},
        new WordSet {InsiderWord = "Bike Tour", OutsiderWord = "Route"},
        new WordSet {InsiderWord = "Surfing", OutsiderWord = "Board"},
        new WordSet {InsiderWord = "Mountain Climbing", OutsiderWord = "Rocks"},
        new WordSet {InsiderWord = "Sailing", OutsiderWord = "Mast"},
        new WordSet {InsiderWord = "Roller Skating", OutsiderWord = "Wheels"},
        new WordSet {InsiderWord = "Cycling", OutsiderWord = "Chain"},
        new WordSet {InsiderWord = "Painting", OutsiderWord = "Frame"},
        new WordSet {InsiderWord = "Drawing", OutsiderWord = "Pencil"},
        new WordSet {InsiderWord = "Podcast", OutsiderWord = "Voice"},
        new WordSet {InsiderWord = "Summer Festival", OutsiderWord = "Fireworks"},
        new WordSet {InsiderWord = "Drumming", OutsiderWord = "Sticks"},
        new WordSet {InsiderWord = "Garden Party", OutsiderWord = "Lanterns"},
        new WordSet {InsiderWord = "Theme Park", OutsiderWord = "Rides"},
        new WordSet {InsiderWord = "Carnival", OutsiderWord = "Costume"},
        new WordSet {InsiderWord = "Beach Walk", OutsiderWord = "Shell"},
        new WordSet {InsiderWord = "Mountain Bike", OutsiderWord = "Tires"},
        new WordSet {InsiderWord = "Playing Piano", OutsiderWord = "Notes"},
        new WordSet {InsiderWord = "Sculpting", OutsiderWord = "Clay"},
        new WordSet {InsiderWord = "Book Club", OutsiderWord = "Chapter"},
        new WordSet {InsiderWord = "Marketplace", OutsiderWord = "Ad"},
        new WordSet {InsiderWord = "Chess Tournament", OutsiderWord = "Board"},
        new WordSet {InsiderWord = "Summer Camp", OutsiderWord = "Friendship"},
        new WordSet {InsiderWord = "Group Photo", OutsiderWord = "Smile"},
        new WordSet {InsiderWord = "Singing Contest", OutsiderWord = "Voice"},
        new WordSet {InsiderWord = "Street Dance", OutsiderWord = "Moves"},
        new WordSet {InsiderWord = "Beach Volleyball", OutsiderWord = "Net"},
        new WordSet {InsiderWord = "Diving", OutsiderWord = "Flippers"},
        new WordSet {InsiderWord = "Road Trip", OutsiderWord = "Map"},
        new WordSet {InsiderWord = "Climbing Park", OutsiderWord = "Harness"},
        new WordSet {InsiderWord = "Board Game", OutsiderWord = "Dice"},
        new WordSet {InsiderWord = "Camping", OutsiderWord = "Fire"},
        new WordSet {InsiderWord = "Street Food", OutsiderWord = "Stall"},
        new WordSet {InsiderWord = "Gardening", OutsiderWord = "Shovel"},
        new WordSet {InsiderWord = "Sunbathing", OutsiderWord = "Towel"},
        new WordSet {InsiderWord = "Winter Walk", OutsiderWord = "Scarf"},
        new WordSet {InsiderWord = "Movie Night", OutsiderWord = "Couch"},
        new WordSet {InsiderWord = "Photo Walk", OutsiderWord = "Nature"},
        new WordSet {InsiderWord = "Bouldering", OutsiderWord = "Wall"},
        new WordSet {InsiderWord = "Airsoft", OutsiderWord = "Mask"},
        new WordSet {InsiderWord = "Cooking Club", OutsiderWord = "Recipes"},
        new WordSet {InsiderWord = "Christmas Market", OutsiderWord = "Stalls"},
        new WordSet {InsiderWord = "Campfire", OutsiderWord = "Flames"},
        new WordSet {InsiderWord = "Halloween", OutsiderWord = "Shadow"},
        new WordSet {InsiderWord = "Drawing Contest", OutsiderWord = "Portrait"},
        new WordSet {InsiderWord = "Easter Egg Hunt", OutsiderWord = "Basket"},
        new WordSet {InsiderWord = "Gala", OutsiderWord = "Dress"},
        new WordSet {InsiderWord = "Geocaching", OutsiderWord = "Treasure"},
        new WordSet {InsiderWord = "Boules", OutsiderWord = "Ball"},
        new WordSet {InsiderWord = "Summer Vacation", OutsiderWord = "Suitcase"},
        new WordSet {InsiderWord = "Swimming Lessons", OutsiderWord = "Strokes"},
        new WordSet {InsiderWord = "Building Lego", OutsiderWord = "Blocks"},
        new WordSet {InsiderWord = "Model Trains", OutsiderWord = "Tracks"},
        new WordSet {InsiderWord = "Parkour", OutsiderWord = "Wall"},
        new WordSet {InsiderWord = "Bungee Jumping", OutsiderWord = "Depth"},
        new WordSet {InsiderWord = "Water Polo", OutsiderWord = "Ball"},
        new WordSet {InsiderWord = "Foam Party", OutsiderWord = "Bubbles"},
        new WordSet {InsiderWord = "Street Food Market", OutsiderWord = "Smells"},
        new WordSet {InsiderWord = "Video Editing", OutsiderWord = "Clips"},
        new WordSet {InsiderWord = "Basketball Game", OutsiderWord = "Dribble"},
        new WordSet {InsiderWord = "Zoo", OutsiderWord = "Cage"},
        new WordSet {InsiderWord = "Dune Walk", OutsiderWord = "Sand"},
        new WordSet {InsiderWord = "Film Festival", OutsiderWord = "Premiere"},
        new WordSet {InsiderWord = "Water Balloon Fight", OutsiderWord = "Splashes"},
        new WordSet {InsiderWord = "Night Swimming", OutsiderWord = "Stars"},
        new WordSet {InsiderWord = "Trampoline Jumping", OutsiderWord = "Bounces"},
        new WordSet {InsiderWord = "Street Art", OutsiderWord = "Graffiti"},
        new WordSet {InsiderWord = "Tattoo", OutsiderWord = "Needle"},
        new WordSet {InsiderWord = "Graffiti", OutsiderWord = "Spray Can"},
        new WordSet {InsiderWord = "Midsummer Festival", OutsiderWord = "Torches"},
        new WordSet {InsiderWord = "Fireworks Show", OutsiderWord = "Bang"},
        new WordSet {InsiderWord = "Parachuting", OutsiderWord = "Fall"},
        new WordSet {InsiderWord = "Snorkeling", OutsiderWord = "Fish"},
        new WordSet {InsiderWord = "Climbing Hall", OutsiderWord = "Holds"},
        new WordSet {InsiderWord = "River Walk", OutsiderWord = "Stones"},
        new WordSet {InsiderWord = "City Walk", OutsiderWord = "Guide"},
        new WordSet {InsiderWord = "Beach Volleyball", OutsiderWord = "Sand"},
        new WordSet {InsiderWord = "Coffee Shop", OutsiderWord = "Beans"},
        new WordSet {InsiderWord = "Hot Air Balloon Ride", OutsiderWord = "Basket"},
        new WordSet {InsiderWord = "Sandcastles", OutsiderWord = "Shovel"},
        new WordSet {InsiderWord = "Paintball", OutsiderWord = "Mask"},
        new WordSet {InsiderWord = "Park Festival", OutsiderWord = "Blankets"},
        new WordSet {InsiderWord = "Drone Show", OutsiderWord = "Figures"},
        new WordSet {InsiderWord = "Magic Tricks", OutsiderWord = "Cards"},
        new WordSet {InsiderWord = "Magic Show", OutsiderWord = "Illusion"},
        new WordSet {InsiderWord = "Circus", OutsiderWord = "Clown"},
        new WordSet {InsiderWord = "Ferris Wheel", OutsiderWord = "View"},
        new WordSet {InsiderWord = "Stargazing", OutsiderWord = "Telescope"},
        new WordSet {InsiderWord = "Rafting", OutsiderWord = "Wood"},
        new WordSet {InsiderWord = "Werewolf Game", OutsiderWord = "Cards"},
        new WordSet {InsiderWord = "Candle Making", OutsiderWord = "Wax"},
        new WordSet {InsiderWord = "Circle Game", OutsiderWord = "Circle"},
        new WordSet {InsiderWord = "Beachcombing", OutsiderWord = "Treasures"},
        new WordSet {InsiderWord = "Lantern Parade", OutsiderWord = "Lights"},
        new WordSet {InsiderWord = "Canoeing", OutsiderWord = "Paddle"},
        new WordSet {InsiderWord = "Horse Racing", OutsiderWord = "Finish"},
        new WordSet {InsiderWord = "Sandbox Play", OutsiderWord = "Molds"},
        new WordSet {InsiderWord = "Picnic", OutsiderWord = "Basket"},
        new WordSet {InsiderWord = "Bouncy Castle Party", OutsiderWord = "Jumping"},
        new WordSet {InsiderWord = "Photo Collage", OutsiderWord = "Scrapbook"},
        new WordSet {InsiderWord = "Kite Competition", OutsiderWord = "String"},
        new WordSet {InsiderWord = "Bird Watching", OutsiderWord = "Binoculars"},
        new WordSet {InsiderWord = "Lantern Festival", OutsiderWord = "Glow"},
        new WordSet {InsiderWord = "Adventure Park", OutsiderWord = "Climbing"}
    };

    public static WordSet GetRandomSet()
    {
        var locale = LocalizationSettings.SelectedLocale;
        var sets = locale.Identifier.Code == "en" ? sets_en : sets_nl;
        int index = random.Next(sets.Count);
        return sets[index];
    }
}

public class WordSet
{
    public string InsiderWord { get; set; }
    public string OutsiderWord { get; set; }

    public override string ToString()
    {
        return $"InsiderWord: {InsiderWord}, OutsiderWord: {OutsiderWord}";
    }
}
